version: '3.8'

services:
  backend:
    build: ./backend
    container_name: haylou-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/haylou
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: haylou-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: haylou-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=haylou
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
